version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-asset
    ports:
      - "6603:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: asset_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: backend-asset
    ports:
      - "3043:3043"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: asset_management
      PORT: 3043
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: frontend-asset
    ports:
      - "8142:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr:
    build: ./HR
    container_name: hr-asset
    ports:
      - "8143:80"
    depends_on:
      - backend
    restart: unless-stopped

  request:
    build: ./Request
    container_name: request-asset
    ports:
      - "8144:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

